local core = require("jester.core")
describe("core", function()
  setup(function()
    core.bootstrap_test()
  end)
  describe("logger", function()
    it("outputs correct level", function()
      level, output = core.log.info("test")
      assert.is.equal(level, "info")
    end)
    it("outputs default prefix", function()
      level, output = core.log.info("test")
      assert.is.equal(output, "[JESTER] test")
    end)
  end)
end)
