#!/bin/sh

# Helper script to make calling Jester help less typing intensive.
#
# See 'help scripts jhelp' in the Jester help system for setup instructions.

FREESWITCH_SCRIPTS_DIR="/usr/local/freeswitch/scripts"

CURRENT_DIR=`pwd`
cd $FREESWITCH_SCRIPTS_DIR
lua jester/jester.lua 'help' $@
cd $CURRENT_DIR

